---

# Whether to track stats on the performance of the
# Cache server
enableStats: true
historyFile: "~/.shotgunCacheHistory"
indexNameTemplate: "shotgun-entity-{type}"

elastic:
    init:
        hosts:
            - localhost
        sniff_on_start: true

entityConfigManager:
    configFolder: ./entities

entityImport:
    processes: 8
    zmqPullUrl: tcp://0.0.0.0:5558
    zmqPostUrl: tcp://0.0.0.0:5559
    batchSize: 250


shotgun:
    base_url: https://moonbotstudios.shotgunstudio.com
    script_name: shotgunEventDaemon
    api_key: 27c98a581326e3e85df1ef271991db0a4a737838

monitor:
    zmqPostUrl: tcp://0.0.0.0:5557

